# Generated by Django 6.0.3 on 2026-03-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80, verbose_name='Nombre visible')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID externo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='players/avatars/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['display_name'],
            },
        ),
    ]
