# Generated by Django 6.0.3 on 2026-03-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID externo')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('finished', 'Finalizado')], default='draft', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-date', '-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID externo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('finished', 'Finalizada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
                'ordering': ['tournament', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID externo')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Victorias')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Derrotas')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Empates')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('final_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Posición final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_entries', to='catalog.legend', verbose_name='Leyenda')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='users.player', verbose_name='Jugador')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['tournament', 'player'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID externo')),
                ('table_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mesa')),
                ('player1_wins', models.PositiveIntegerField(default=0, verbose_name='Victorias jugador 1')),
                ('player2_wins', models.PositiveIntegerField(default=0, verbose_name='Victorias jugador 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round', verbose_name='Ronda')),
                ('player1_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='tournaments.tournamententry', verbose_name='Jugador 1')),
                ('player2_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='tournaments.tournamententry', verbose_name='Jugador 2')),
            ],
            options={
                'verbose_name': 'Enfrentamiento',
                'verbose_name_plural': 'Enfrentamientos',
                'ordering': ['round', 'table_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='unique_round_number_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamententry',
            constraint=models.UniqueConstraint(fields=('tournament', 'player'), name='unique_player_per_tournament'),
        ),
    ]
