# Generated by Django 6.0.3 on 2026-03-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_set'),
        ('tournaments', '0002_tournament_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='catalog.set', verbose_name='Set'),
            preserve_default=False,
        ),
    ]
